;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
aseprite="C:\Program Files\Aseprite\Aseprite.exe"
nvim=nvim-qt.exe --fullscreen --no-ext-tabline --timeout 5000 $*
nvim_window=nvim-qt.exe --no-ext-tabline --timeout 5000 $*
colors=sh colors.sh
kill_useless=sh kill_useless.sh $*
ls=ls -F --color --almost-all $*
task=bash -c "task $*"
sst=sh status.sh
cd_home=cd C:\Users\Luke\
cd_nvim=cd C:\Users\Luke\AppData\Local\nvim\
cd_repos=cd C:\Users\Luke\source\repos\
run_ge=cd C:\Users\Luke\ && sh run.sh grimoire-editor && cd source\repos\Grimoire-Workspace\
smega=sh mega.sh
cds=cd $* && git status
